"""CV pipeline: resumes -> ATS-friendly CVs, optionally tailored to one job.

Usage:
    py main.py -input <input_folder> -output <output_folder> [-jd <job_description_file>]

Reads every resume .txt file from the input folder and writes an ATS-friendly
CV (.docx/.pdf) plus stage JSON for each resume into the output folder.

  -jd given:    each CV is matched against that job description and tailored
                to it (GenerateCV), using only evidence the resume can prove.
  -jd omitted:  each CV is generated by polishing the candidate's own stated
                facts only (ProfessionalCVGenerator) - no target job.

Resumable: a resume whose extracted/generated JSON already exists in the
output folder is loaded instead of re-run, so an interrupted batch can
continue without redoing work.
"""

import argparse
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

from extract_and_parse import ExtractResume, ParseJob
from generate_profile_cv import ProfessionalCVGenerator
from match_skills import MatchSkills
from retrieve_evidence import RetrieveEvidence
from generate_tailored_cv import GenerateCV
from quality_check import check_extraction, check_generated_cv
from render_document import DocumentGenerator
from json_utils import save_json, load_json


def parse_args():
    parser = argparse.ArgumentParser(description="Generate ATS-friendly CVs, optionally tailored to a job.")
    parser.add_argument("-input", dest="input_dir", required=True, help="Folder containing resume .txt files")
    parser.add_argument("-output", dest="output_dir", required=True, help="Folder to write generated CVs and stage JSON")
    parser.add_argument("-jd", dest="jd_path", default=None,
                         help="Path to a job description .txt file (optional - omit to polish each "
                              "resume on its own, with no target job)")
    return parser.parse_args()


def process_resume(resume_path, job_data, output_dir, extractor, matcher, retriever, generator, renderer):
    stem = resume_path.stem
    extracted_path = output_dir / f"{stem}_extracted_resume.json"
    generated_path = output_dir / f"{stem}_generated_cv.json"

    if extracted_path.exists():
        resume_data = load_json(extracted_path)
    else:
        resume_data = extractor.run(resume_path.read_text(encoding="utf-8"))
        if not resume_data:
            return "extraction failed: Llama 2 did not return valid JSON"
        save_json(extracted_path, resume_data)

    issues = check_extraction(resume_data)

    if generated_path.exists():
        generated_cv = load_json(generated_path)
    elif job_data:
        match_data = matcher.run(resume_data, job_data)
        save_json(output_dir / f"{stem}_match.json", match_data)

        evidence_data = retriever.run(resume_data, match_data)
        save_json(output_dir / f"{stem}_evidence.json", evidence_data)

        generated_cv = generator.run(resume_data, job_data, match_data, evidence_data)
        if not generated_cv:
            return "generation failed: Gemma 3 did not return valid JSON"
        save_json(generated_path, generated_cv)

        if match_data["fabrication_blocklist"]:
            print(f"    Could not prove (excluded from CV): {', '.join(match_data['fabrication_blocklist'])}")
    else:
        generated_cv = generator.run(resume_data)
        if not generated_cv:
            return "generation failed: Gemma 3 did not return valid JSON"
        save_json(generated_path, generated_cv)

    issues += check_generated_cv(generated_cv, resume_data)

    if job_data:
        heading = f"Experience - tailored for {job_data.get('title', '')} at {job_data.get('company', '')}"
        filename_suffix = job_data.get("company", "")
    else:
        heading, filename_suffix = "Experience", ""

    paths = renderer.run(
        resume_data, generated_cv, str(output_dir),
        experience_heading=heading, filename_suffix=filename_suffix,
    )

    print(f"  {resume_path.name} -> {paths['docx_path']}" + (f"  [warnings: {', '.join(issues)}]" if issues else ""))
    return None


def main():
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)

    if not input_dir.is_dir():
        print(f"Input folder not found: {input_dir}")
        return

    resume_files = sorted(input_dir.glob("*.txt"))
    if not resume_files:
        print(f"No resume .txt files found in {input_dir}")
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Parsing Sample Resumes from {input_dir}")

    job_data = None
    if args.jd_path:
        jd_path = Path(args.jd_path)
        if not jd_path.is_file():
            print(f"Job description file not found: {jd_path}")
            return
        print(f"Parsing JD from {jd_path}")
        job_data = ParseJob().run(jd_path.read_text(encoding="utf-8"))
        if not job_data:
            print("JD parsing failed: Llama 2 did not return valid JSON")
            return
        save_json(output_dir / "parsed_job_description.json", job_data)

    extractor = ExtractResume()
    matcher = MatchSkills() if job_data else None
    retriever = RetrieveEvidence() if job_data else None
    generator = GenerateCV() if job_data else ProfessionalCVGenerator()
    renderer = DocumentGenerator()

    print(f"Creating ATS friendly Resumes in {output_dir}")
    failures = []
    for resume_path in resume_files:
        try:
            error = process_resume(resume_path, job_data, output_dir, extractor, matcher, retriever, generator, renderer)
        except Exception as e:
            error = f"crashed: {e}"
        if error:
            failures.append((resume_path.name, error))
            print(f"  FAILED {resume_path.name}: {error}")

    ok = len(resume_files) - len(failures)
    print(f"\nCompleted: {ok}/{len(resume_files)} ATS-friendly CVs generated in {output_dir}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Cancelled")
