"""CV pipeline: resumes -> ATS-friendly CVs, optionally tailored to one job.

Usage:
    py main.py -input <input_folder> -output <output_folder> [-jd <job_description_file>]

Reads every resume file (.txt, .pdf, or .docx) from the input folder and
writes an ATS-friendly CV (.docx/.pdf) plus stage JSON for each resume into
the output folder. The job description file may also be .txt, .pdf, or .docx.

  -jd given:    each CV is matched against that job description and tailored
                to it (GenerateCV), using only evidence the resume can prove.
  -jd omitted:  each CV is generated by polishing the candidate's own stated
                facts only (ProfessionalCVGenerator) - no target job.

Resumable: a resume whose extracted/generated JSON already exists in the
output folder is loaded instead of re-run, so an interrupted batch can
continue without redoing work.

Runs in two batched phases rather than interleaving per resume: all
extractions (Llama 2) first, then all generations (Gemma 3). The two
models don't both fit in VRAM on modest hardware, so alternating them
per resume forces a reload every time; batching keeps each model loaded
for its whole phase instead of swapping 2x per resume.

Pass -review to inspect each generated CV interactively before it's
finalised: it prints ATS coverage (tailored mode), which matched skills
don't actually appear in the rendered Skills line, and quality_check
warnings, then lets you type free-text feedback to have the LLM revise the
CV (still constrained to the same evidence/blocklist), looping until you
accept it by pressing Enter.

Pass -printJson to also print every stage's JSON (parsed job description,
extracted resume, match, evidence, generated CV) to stdout as it's produced
or loaded. Omit it and only the normal progress/summary lines are printed.
"""

import argparse
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", line_buffering=True)

from document_reader import read_text, SUPPORTED_EXTENSIONS
from extract_and_parse import ExtractResume, ParseJob
from generate_profile_cv import ProfessionalCVGenerator
from match_skills import MatchSkills
from retrieve_evidence import RetrieveEvidence
from generate_tailored_cv import GenerateCV
from quality_check import check_extraction, check_generated_cv
from render_document import DocumentGenerator
from json_utils import save_json, load_json


def parse_args():
    parser = argparse.ArgumentParser(description="Generate ATS-friendly CVs, optionally tailored to a job.")
    parser.add_argument("-input", dest="input_dir", required=True,
                         help="Folder containing resume files (.txt, .pdf, or .docx)")
    parser.add_argument("-output", dest="output_dir", required=True, help="Folder to write generated CVs and stage JSON")
    parser.add_argument("-jd", dest="jd_path", default=None,
                         help="Path to a job description file (.txt, .pdf, or .docx - optional, "
                              "omit to polish each resume on its own, with no target job)")
    parser.add_argument("-review", dest="review", action="store_true",
                         help="Interactively review/refine each generated CV before finalising it")
    parser.add_argument("-printJson", dest="print_json", action="store_true",
                         help="Print every stage's JSON (parsed job description, extracted resume, "
                              "match, evidence, generated CV) to stdout as it's produced or loaded")
    return parser.parse_args()


def print_json(label, data):
    print(f"\n--- {label} (JSON) ---")
    print(json.dumps(data, indent=2, ensure_ascii=False))


def unrendered_matched_skills(generated_cv, match_data):
    """Required skills match_skills.py confirmed the resume can prove, that
    don't actually appear in this CV's rendered Skills line - the gap between
    what was matched and what an ATS keyword-scan of the document would see."""
    if not match_data:
        return []
    rendered = {s.lower() for s in generated_cv.get("ordered_skills", [])}
    return [s for s in match_data["required"]["matched"] if s.lower() not in rendered]


def print_review_report(generated_cv, resume_data, job_data, match_data, issues):
    print("\n--- Current CV ---")
    print(f"Summary: {generated_cv.get('summary', '')}")
    for job in generated_cv.get("experience", []):
        print(f"{job.get('position', '')} - {job.get('company', '')} ({job.get('duration', '')})")
        for bullet in job.get("bullets", []):
            print(f"  - {bullet}")
    print(f"Skills: {', '.join(generated_cv.get('ordered_skills', []))}")

    if job_data and match_data:
        print(f"ATS coverage: required {match_data['required']['coverage_pct']}%, "
              f"preferred {match_data['preferred']['coverage_pct']}%")
        gap = unrendered_matched_skills(generated_cv, match_data)
        if gap:
            print(f"Matched skills missing from this CV's Skills line: {', '.join(gap)}")
        if match_data["fabrication_blocklist"]:
            print(f"Cannot prove (excluded): {', '.join(match_data['fabrication_blocklist'])}")
    if issues:
        print(f"Quality warnings: {', '.join(issues)}")


def review_loop(generated_cv, resume_data, job_data, match_data, evidence_data, generator):
    while True:
        issues = check_generated_cv(generated_cv, resume_data)
        print_review_report(generated_cv, resume_data, job_data, match_data, issues)

        feedback = input("\nFeedback to refine this CV, or Enter to accept: ").strip()
        if not feedback:
            return generated_cv

        if job_data:
            revised = generator.refine(generated_cv, feedback, evidence_data)
        else:
            revised = generator.refine(generated_cv, feedback, resume_data)

        if revised is None:
            print("Refinement failed: model did not return valid JSON. Try rephrasing the feedback.")
            continue
        generated_cv = revised


def extract_resume(resume_path, output_dir, extractor, print_json_flag=False):
    """Extract (or load cached) structured resume data. Returns
    (resume_data, issues, error) - error is set (and the other two are None)
    on failure."""
    stem = resume_path.stem
    extracted_path = output_dir / f"{stem}_extracted_resume.json"

    if extracted_path.exists():
        resume_data = load_json(extracted_path)
    else:
        resume_data = extractor.run(read_text(resume_path))
        if not resume_data:
            return None, None, "extraction failed: Llama 2 did not return valid JSON"
        save_json(extracted_path, resume_data)

    if print_json_flag:
        print_json(f"{resume_path.name} extracted_resume", resume_data)

    return resume_data, check_extraction(resume_data), None


def generate_resume(resume_path, resume_data, issues, job_data, output_dir, matcher, retriever, generator, renderer, review=False, print_json_flag=False):
    stem = resume_path.stem
    generated_path = output_dir / f"{stem}_generated_cv.json"
    match_path = output_dir / f"{stem}_match.json"
    evidence_path = output_dir / f"{stem}_evidence.json"

    match_data, evidence_data = None, None

    if generated_path.exists():
        generated_cv = load_json(generated_path)
        if job_data and match_path.exists():
            match_data = load_json(match_path)
        if job_data and evidence_path.exists():
            evidence_data = load_json(evidence_path)
    elif job_data:
        match_data = matcher.run(resume_data, job_data)
        save_json(match_path, match_data)

        evidence_data = retriever.run(resume_data, match_data)
        save_json(evidence_path, evidence_data)

        generated_cv = generator.run(resume_data, job_data, match_data, evidence_data)
        if not generated_cv:
            return "generation failed: Gemma 3 did not return valid JSON"
        save_json(generated_path, generated_cv)

        if match_data["fabrication_blocklist"]:
            print(f"    Could not prove (excluded from CV): {', '.join(match_data['fabrication_blocklist'])}")
    else:
        generated_cv = generator.run(resume_data)
        if not generated_cv:
            return "generation failed: Gemma 3 did not return valid JSON"
        save_json(generated_path, generated_cv)

    if review:
        generated_cv = review_loop(generated_cv, resume_data, job_data, match_data, evidence_data, generator)
        save_json(generated_path, generated_cv)

    if print_json_flag:
        if match_data is not None:
            print_json(f"{resume_path.name} match", match_data)
        if evidence_data is not None:
            print_json(f"{resume_path.name} evidence", evidence_data)
        print_json(f"{resume_path.name} generated_cv", generated_cv)

    issues += check_generated_cv(generated_cv, resume_data)

    if job_data:
        heading = f"Experience - tailored for {job_data.get('title', '')} at {job_data.get('company', '')}"
        filename_suffix = job_data.get("company", "")
    else:
        heading, filename_suffix = "Experience", ""

    paths = renderer.run(
        resume_data, generated_cv, str(output_dir),
        experience_heading=heading, filename_suffix=filename_suffix,
    )

    print(f"  {resume_path.name} -> {paths['docx_path']}" + (f"  [warnings: {', '.join(issues)}]" if issues else ""))
    return None


def main():
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)

    if not input_dir.is_dir():
        print(f"Input folder not found: {input_dir}")
        return

    resume_files = sorted(p for ext in SUPPORTED_EXTENSIONS for p in input_dir.glob(f"*{ext}"))
    if not resume_files:
        print(f"No resume files ({', '.join(SUPPORTED_EXTENSIONS)}) found in {input_dir}")
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Parsing Sample Resumes from {input_dir}")

    job_data = None
    if args.jd_path:
        jd_path = Path(args.jd_path)
        if not jd_path.is_file():
            print(f"Job description file not found: {jd_path}")
            return
        print(f"Parsing JD from {jd_path}")
        try:
            job_text = read_text(jd_path)
        except ValueError as e:
            print(f"Job description file not readable: {e}")
            return
        job_data = ParseJob().run(job_text)
        if not job_data:
            print("JD parsing failed: Llama 2 did not return valid JSON")
            return
        save_json(output_dir / "parsed_job_description.json", job_data)
        if args.print_json:
            print_json("parsed_job_description", job_data)

    # Phase 1: extract every resume with Llama 2 before touching Gemma 3 at
    # all, so the extraction model stays loaded for the whole batch instead
    # of swapping with the generation model on every single resume.
    extractor = ExtractResume()
    extracted = []
    failures = []
    for resume_path in resume_files:
        print(f"Parsing {resume_path.name}")
        try:
            resume_data, issues, error = extract_resume(resume_path, output_dir, extractor, print_json_flag=args.print_json)
        except Exception as e:
            resume_data, issues, error = None, None, f"crashed: {e}"
        if error:
            failures.append((resume_path.name, error))
            print(f"  FAILED {resume_path.name}: {error}")
        else:
            extracted.append((resume_path, resume_data, issues))

    # Phase 2: generate every CV with Gemma 3, now that Llama 2 is done.
    matcher = MatchSkills() if job_data else None
    retriever = RetrieveEvidence() if job_data else None
    generator = GenerateCV() if job_data else ProfessionalCVGenerator()
    renderer = DocumentGenerator()

    print(f"Creating ATS friendly Resumes in {output_dir}")
    for resume_path, resume_data, issues in extracted:
        try:
            error = generate_resume(resume_path, resume_data, issues, job_data, output_dir, matcher, retriever, generator, renderer, review=args.review, print_json_flag=args.print_json)
        except Exception as e:
            error = f"crashed: {e}"
        if error:
            failures.append((resume_path.name, error))
            print(f"  FAILED {resume_path.name}: {error}")

    ok = len(resume_files) - len(failures)
    print(f"\nCompleted: {ok}/{len(resume_files)} ATS-friendly CVs generated in {output_dir}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Cancelled")
